### PR TITLE
[Feature] Add workaround class for RecyclerView's touch event dispatch.

### LINKED ISSUE #13: Incompatible with androidx.recyclerview.selection
## Expected Behavior
When AndroidFastScroll is applied to a RecyclerView that has a SelectionTracker set, using the fast scroller should not lead to rows being selected.

## Actual Behavior
Scrolling randomly selects rows in the RecyclerView.

## Steps to Reproduce the Problem

1. `recyclerView.setSelectionTracker(...)`
2. `FastScrollerBuilder(recyclerView).build()`
3. Scroll through the RecyclerView with the fast scroller.

## Specifications

- Version: 1.1.2
- Platform: Android 9

### PR DESCRIPTION
**Pull request by FabianHenneke**
Fixes #13.

> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by FabianHenneke** [comment]
Is there a chance for a new release before April 21? If not, I would add this manually to the app where I first experienced the issue.

**Comment by zhanghai** [comment]
Please manually add it to the app - I'd like to implement this slight differently.

**Comment by FabianHenneke** [comment]
We've successfully included this in our release, but will switch to your solution once it's ready. Thanks!

**Comment by zhanghai** [comment]
@FabianHenneke Could you please try if 97993e2 works for your project?

**Comment by FabianHenneke** [comment]
I can confirm that this fixes the scrolling issue in my project. Thanks for the conceptual fix!

Might https://github.com/zhanghai/AndroidFastScroll/commit/8a06dc9a9191d361e8948550810b343f7d9ba669#diff-942a927a29fb1b75478e94d30f602f2cR126 cause a NPE if no `OnItemTouchListener` is ever registered, e.g. if `FastScroller` is disabled at some point but this class is left in?

**Comment by zhanghai** [comment]
Generally it would not be possible, unless someone removes their listener during touch event processing. I'll add a check to defend against this.

**Comment by FabianHenneke** [comment]
Thanks! We will switch to the new version once it is released and continue to report any problems we see.

**Comment by zhanghai** [comment]
v1.3.3 has been released.

**Pull request closed without merging**
