### PR TITLE
Fix setViewHelper() does not return FastScrollerBuilder

### PR DESCRIPTION
**Pull request by drakeet**

### CODE REVIEW

**Comment by drakeet** [comment]
This looks like an obvious mistake, so I just directly sent the small PR (Sorry for no issue first). BTW, this project is great, hope it can be better and support multiple item view types in one RecycerView.

**Comment by zhanghai** [comment]
lol yes, I overlooked this when adding that method. Thanks for finding it out!

However, you will need to [sign the CLA](https://github.com/zhanghai/AndroidFastScroll/blob/master/docs/contributing.md) before I can merge this PR. If you don't want the trouble, I can also just go ahead and fix it myself. What do you think?

**Comment by zhanghai** [comment]
If you want multipe view type support you can create your own `ViewHelper`, buliding upon the `RecyclerViewHelper`. It's kinda complex to compute all those things (esp. combined with grid support) and there are much more to be customizable (e.g. use existing view if possible? maybe ask recycler as well?) so I just didn't include it.

**Comment by drakeet** [comment]
OK, I have signed it.

**Comment by drakeet** [comment]
And tried the ViewHelper (so I found the problem), It's not easy to implement the multiple types support, I simply tried it, the result is not ideal, maybe I will try again.

**Comment by zhanghai** [comment]
Thanks!

**Comment by zhanghai** [comment]
Released [v1.0.4](https://github.com/zhanghai/AndroidFastScroll/releases/tag/v1.0.4).

**Pull request merged**
